name: Deploy to Vercel

# Esto hace que el workflow se ejecute al hacer push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    # Exponemos los IDs como variables de entorno para la CLI de Vercel
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Cambia esto por la versión que use tu proyecto

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Obtener información del entorno de Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir el proyecto (Build)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Desplegar en Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}